### ISSUE TITLE
云引擎 Java 运行环境解析云函数参数有问题

### ISSUE THREAD

**Issue by sdjcw** [leancloud/leanengine-java-sdk#38]
只有一个参数的时候，且传递参数的名称和定义不一致时，定义的参数将接收到一个完整的 json 字符串。

如果由多个参数，且传递参数名称和定义不一致时，会抛出异常，用户希望能是 null。

https://leanticket.cn/t/leancloud/4964

**Comment by daweibayu** [comment]
solved in [0.2.0](https://github.com/leancloud/leanengine-java-sdk/releases/tag/0.2.0)
